### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by teenjuna** [bleusakura/magnetfinder#2]
Hi! I think it would be nice to support proxies, since torrent trackers are blocked in some countries. I haven't look at your code, but `Cargo.toml` indicates that you use `reqwest`, which does support proxies. I would start from `socks`, since it allows one to use `tor`. Do you need help with that?

**Comment by bleusakura** [comment]
Seems like a good idea, one that I would like to add. I'll look into the reqwest docs for information on how to implement this, hopefully won't be too complicated. I have been rather busy lately so not sure when ill get to it but hopefully in the next few days or so.

**Comment by bleusakura** [comment]
@teenjuna I just pushed this commit 15393fcd67f0af46dcd93e02ff6d6dbd6e155493 , let me know if it works for you and if there is anything you think would be good to change.

You can either delete your old config file and let a new one be generated, or just add the variable ```default_proxy``` and set it to socks5://ip:port

**Comment by teenjuna** [comment]
Hi again! This works like a charm. The only thing you might want to change is to remove `(socks5)` part from the help message, since you can also use `http` and `https` proxies

**Comment by bleusakura** [comment]
Awesome to hear, and good catch on the help message part; I had intended to remove it but forgot!
